// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Suite1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void t1() {
    driver.Navigate().GoToUrl("https://www.selenium.dev/selenium-ide/");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 864);
    driver.FindElement(By.LinkText("Docs")).Click();
    Assert.That(driver.Title, Is.EqualTo("Getting Started · Selenium IDE"));
    driver.Close();
  }
  [Test]
  public void t2() {
    driver.Navigate().GoToUrl("https://www.selenium.dev/");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 864);
    driver.FindElement(By.CssSelector(".selenium-ide > .pl-3")).Click();
    driver.FindElement(By.LinkText("Help")).Click();
    driver.FindElement(By.CssSelector(".docMainWrapper")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Need help?"));
    driver.Close();
  }
}
